### ISSUE TITLE
提现10天没到账

### ISSUE THREAD

**Issue by chengxulvtu** [HcashOrg/hx-indicator#4]
hx-indicator提现eth到充值地址，10天还没到账

http://explorer.hx.cash/#/transfer_details/9b6dc4aaf9b0709364b7a4ae0c2ad85bac054c33/61

**Comment by ElleryHao** [comment]
![image](https://user-images.githubusercontent.com/5901807/61932269-7ea20700-afb5-11e9-8679-95aebf7f9d99.png)

**Comment by ElleryHao** [comment]
看浏览器是已经收到了啊

**Comment by ElleryHao** [comment]
这个是交易所地址吗？

**Comment by chengxulvtu** [comment]
> 这个是交易所地址吗？

这是hx-indicator生成的充值地址。我刚刚查了到账了。好多天了，忽然想起来了，看到miner还为空以为还没到呢
